# Generated by Django 5.0 on 2023-12-29 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project_UAS', '0002_mata_kuliah_mahasiswa_delete_absen_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='jadwal_hari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('makul', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='absen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50)),
                ('npm', models.CharField(max_length=50)),
                ('fakultas', models.CharField(max_length=50)),
                ('prodi', models.CharField(max_length=50)),
                ('hari', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Project_UAS.jadwal_hari')),
            ],
        ),
        migrations.DeleteModel(
            name='Mahasiswa',
        ),
        migrations.DeleteModel(
            name='Mata_kuliah',
        ),
    ]
