# Generated by Django 5.0 on 2023-12-31 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project_UAS', '0004_absen_keterangan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absen',
            name='hari',
            field=models.CharField(max_length=50),
        ),
        migrations.AddField(
            model_name='absen',
            name='makul',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='jadwal_hari',
        ),
    ]
