# Generated by Django 5.0 on 2023-12-31 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project_UAS', '0005_alter_absen_hari_absen_makul_delete_jadwal_hari'),
    ]

    operations = [
        migrations.AddField(
            model_name='absen',
            name='no',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
